-- MYSQL-OBJ-012: Cleanup

DROP TRIGGER IF EXISTS `obj012_bi`;
DROP TRIGGER IF EXISTS `obj012_ai`;
DROP TRIGGER IF EXISTS `obj012_bu`;
DROP TRIGGER IF EXISTS `obj012_au`;
DROP TRIGGER IF EXISTS `obj012_bd`;
DROP TRIGGER IF EXISTS `obj012_ad`;
DROP TABLE IF EXISTS `obj012_audit`;
DROP TABLE IF EXISTS `obj012_data`;
