package ai.chat2db.community.updater;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.awt.Desktop;
import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

/**
 * The elevated Windows updater. Its input is generated by the desktop process,
 * but it validates every filesystem operation again before modifying APP_DIR.
 */
public final class ExternalUpdater {
    static final long MAX_SINGLE_FILE_BYTES = 2L * 1024 * 1024 * 1024;
    static final long MAX_TOTAL_DOWNLOAD_BYTES = 4L * 1024 * 1024 * 1024;
    static final int MAX_ZIP_ENTRIES = 20_000;
    static final long MAX_ZIP_UNCOMPRESSED_BYTES = 2L * 1024 * 1024 * 1024;
    private static final String SHA_256_PATTERN = "^[a-fA-F0-9]{64}$";
    private static final String BACKUP_DIRECTORY = ".chat2db-update-backups";
    private static final String BACKUP_OWNER_PID_FILE = ".owner-pid";
    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    private ExternalUpdater() {
    }

    public static void main(String[] args) {
        int exitCode = run(args);
        System.exit(exitCode);
    }

    static int run(String[] args) {
        if (args.length < 3) {
            log("FATAL: Missing arguments. Usage: updater.jar <plan_path> <app_dir> <restart_uri>");
            return 1;
        }
        Path planPath = Path.of(args[0]).toAbsolutePath().normalize();
        Path appDirectory = Path.of(args[1]).toAbsolutePath().normalize();
        try {
            if (!Files.isRegularFile(planPath, LinkOption.NOFOLLOW_LINKS)) {
                throw new IOException("Update plan file not found or is not a regular file");
            }
            if (!Files.isDirectory(appDirectory, LinkOption.NOFOLLOW_LINKS)) {
                throw new IOException("Application directory is not a regular directory");
            }
            UpdatePlan plan = OBJECT_MAPPER.readValue(planPath.toFile(), UpdatePlan.class);
            executeInstallation(plan, appDirectory);
            if (!restartMainApplication(args[2], appDirectory)) {
                log("WARN: Update installed successfully, but the application could not be restarted automatically.");
            }
            Files.deleteIfExists(planPath);
            return 0;
        } catch (Exception exception) {
            log("FATAL: Update failed: " + exception.getMessage());
            exception.printStackTrace(System.err);
            return 1;
        }
    }

    static void executeInstallation(UpdatePlan plan, Path appDirectory) throws IOException {
        executeInstallation(plan, appDirectory, defaultDownloadDirectory());
    }

    static void executeInstallation(UpdatePlan plan, Path appDirectory, Path downloadDirectory) throws IOException {
        Path controlledDownloadDirectory = downloadDirectory.toAbsolutePath().normalize();
        validatePlan(plan, appDirectory, controlledDownloadDirectory);
        Map<String, Path> downloadedFiles = new HashMap<>();
        for (Map.Entry<String, String> entry : plan.downloadedFiles.entrySet()) {
            downloadedFiles.put(entry.getKey(), Path.of(entry.getValue()).toAbsolutePath().normalize());
        }
        Path backupSession = resolveApplicationPath(appDirectory, BACKUP_DIRECTORY).resolve(UUID.randomUUID().toString());
        Path stagingDirectory = backupSession.resolve(".staging");
        List<Runnable> rollbackOperations = new ArrayList<>();
        try {
            Files.createDirectories(stagingDirectory);
            Files.writeString(backupSession.resolve(BACKUP_OWNER_PID_FILE), Long.toString(ProcessHandle.current().pid()),
                    StandardOpenOption.CREATE_NEW);
            for (FileUpdateAction action : plan.tasks) {
                applyAction(action, downloadedFiles, appDirectory, backupSession, stagingDirectory, rollbackOperations);
            }
            saveLocalVersion(plan.remoteMetadata, appDirectory);
            cleanupCommittedUpdate(downloadedFiles, stagingDirectory);
        } catch (Exception exception) {
            for (int index = rollbackOperations.size() - 1; index >= 0; index--) {
                rollbackOperations.get(index).run();
            }
            for (Path downloadedFile : downloadedFiles.values()) {
                Files.deleteIfExists(downloadedFile);
            }
            throw exception instanceof IOException ? (IOException) exception : new IOException("Failed to apply update", exception);
        }
    }

    private static void applyAction(FileUpdateAction action, Map<String, Path> downloadedFiles, Path appDirectory,
                                    Path backupSession, Path stagingDirectory, List<Runnable> rollbackOperations) throws IOException {
        if ("KEEP_LOCAL".equals(action.actionType)) {
            return;
        }
        FileInfo targetInfo = action.remoteFileInfo != null ? action.remoteFileInfo : action.localFileInfo;
        Path target = resolveApplicationPath(appDirectory, targetInfo.localTargetName);
        if ("DELETE_OLD".equals(action.actionType)) {
            if (Files.exists(target, LinkOption.NOFOLLOW_LINKS)) {
                moveToBackup(target, appDirectory, backupSession, rollbackOperations);
            }
            return;
        }
        if (!"DOWNLOAD_NEW".equals(action.actionType) && !"UPDATE_EXISTING".equals(action.actionType)) {
            throw new IOException("Unsupported update action: " + action.actionType);
        }
        FileInfo remoteFile = action.remoteFileInfo;
        Path downloadedFile = downloadedFiles.get(remoteFile.id);
        verifyDownloadedFile(downloadedFile, remoteFile);
        if (Files.exists(target, LinkOption.NOFOLLOW_LINKS)) {
            moveToBackup(target, appDirectory, backupSession, rollbackOperations);
        } else {
            rollbackOperations.add(() -> deleteQuietly(target));
        }
        if ("zip".equals(remoteFile.type)) {
            Path stageRoot = stagingDirectory.resolve(remoteFile.id);
            extractZip(downloadedFile, stageRoot, target.getFileName().toString());
            Path stagedContent = stageRoot.resolve(target.getFileName().toString());
            if (!Files.isDirectory(stagedContent, LinkOption.NOFOLLOW_LINKS)) {
                throw new IOException("ZIP archive does not contain the expected directory");
            }
            moveIntoPlace(stagedContent, target);
        } else {
            moveIntoPlace(downloadedFile, target);
        }
    }

    private static void validatePlan(UpdatePlan plan, Path appDirectory, Path downloadDirectory) throws IOException {
        if (plan == null || plan.remoteMetadata == null || isBlank(plan.remoteMetadata.version)
                || plan.remoteMetadata.files == null || plan.tasks == null || plan.downloadedFiles == null) {
            throw new IOException("Update plan is incomplete");
        }
        Map<String, FileInfo> metadataFiles = new HashMap<>();
        Set<String> fileIds = new HashSet<>();
        for (FileInfo file : plan.remoteMetadata.files) {
            validateRemoteFile(file, appDirectory, fileIds);
            metadataFiles.put(file.id, file);
        }
        Set<String> actionDownloadIds = new HashSet<>();
        long totalDownloadSize = 0;
        for (FileUpdateAction action : plan.tasks) {
            if (action == null || isBlank(action.actionType)) {
                throw new IOException("Update plan contains an invalid action");
            }
            FileInfo targetInfo = action.remoteFileInfo != null ? action.remoteFileInfo : action.localFileInfo;
            if (targetInfo == null) {
                throw new IOException("Update action has no target file");
            }
            resolveApplicationPath(appDirectory, targetInfo.localTargetName);
            if ("DOWNLOAD_NEW".equals(action.actionType) || "UPDATE_EXISTING".equals(action.actionType)) {
                FileInfo metadataFile = metadataFiles.get(action.remoteFileInfo.id);
                if (metadataFile == null || metadataFile.deleted || !sameManagedFile(metadataFile, action.remoteFileInfo)) {
                    throw new IOException("Update action does not match remote metadata");
                }
                if (!plan.downloadedFiles.containsKey(action.remoteFileInfo.id)) {
                    throw new IOException("Missing downloaded file for " + action.remoteFileInfo.id);
                }
                if (!actionDownloadIds.add(action.remoteFileInfo.id)) {
                    throw new IOException("Update plan downloads the same file more than once");
                }
                try {
                    totalDownloadSize = Math.addExact(totalDownloadSize, action.remoteFileInfo.fileSizeByte);
                } catch (ArithmeticException exception) {
                    throw new IOException("Update download size overflow", exception);
                }
            } else if ("DELETE_OLD".equals(action.actionType)) {
                if (action.localFileInfo == null) {
                    throw new IOException("Delete action has no local file");
                }
                FileInfo metadataFile = metadataFiles.get(action.localFileInfo.id);
                if (metadataFile == null || !metadataFile.deleted || isBlank(metadataFile.localTargetName)
                        || !metadataFile.localTargetName.equals(action.localFileInfo.localTargetName)) {
                    throw new IOException("Delete action is not declared by remote metadata");
                }
            } else if (!"KEEP_LOCAL".equals(action.actionType)) {
                throw new IOException("Unsupported update action: " + action.actionType);
            }
        }
        if (!plan.downloadedFiles.keySet().equals(actionDownloadIds)) {
            throw new IOException("Update plan contains unexpected downloaded files");
        }
        if (totalDownloadSize > MAX_TOTAL_DOWNLOAD_BYTES) {
            throw new IOException("Update plan exceeds the total download limit");
        }
        for (String downloadedFile : plan.downloadedFiles.values()) {
            resolveControlledDownloadPath(downloadDirectory, downloadedFile);
        }
    }

    private static void validateRemoteFile(FileInfo file, Path appDirectory, Set<String> fileIds) throws IOException {
        if (file == null || isBlank(file.id) || !fileIds.add(file.id)) {
            throw new IOException("Update metadata contains a missing or duplicate file id");
        }
        resolveApplicationPath(appDirectory, file.localTargetName);
        if (file.deleted) {
            return;
        }
        if (isBlank(file.sha256) || !file.sha256.matches(SHA_256_PATTERN) || file.fileSizeByte < 0
                || file.fileSizeByte > MAX_SINGLE_FILE_BYTES || (!"jar".equals(file.type) && !"zip".equals(file.type))) {
            throw new IOException("Update metadata is invalid for " + file.id);
        }
    }

    private static boolean sameManagedFile(FileInfo expected, FileInfo actual) {
        return expected.id.equals(actual.id)
                && expected.localTargetName.equals(actual.localTargetName)
                && expected.sha256.equalsIgnoreCase(actual.sha256)
                && expected.type.equals(actual.type)
                && expected.fileSizeByte == actual.fileSizeByte
                && expected.deleted == actual.deleted;
    }

    private static Path defaultDownloadDirectory() {
        String localAppData = System.getenv("LOCALAPPDATA");
        if (isBlank(localAppData)) {
            localAppData = System.getProperty("user.home") + java.io.File.separator + "AppData" + java.io.File.separator + "Local";
        }
        return Path.of(localAppData).resolve("tmp_updater_downloads");
    }

    private static Path resolveControlledDownloadPath(Path downloadDirectory, String fileName) throws IOException {
        if (Files.isSymbolicLink(downloadDirectory)) {
            throw new IOException("Controlled download directory is a symbolic link");
        }
        Path file = Path.of(fileName).toAbsolutePath().normalize();
        if (!file.startsWith(downloadDirectory) || file.equals(downloadDirectory)) {
            throw new IOException("Downloaded update file is outside the controlled download directory");
        }
        Path current = downloadDirectory;
        for (Path segment : downloadDirectory.relativize(file)) {
            current = current.resolve(segment);
            if (Files.isSymbolicLink(current)) {
                throw new IOException("Downloaded update file path contains a symbolic link");
            }
        }
        return file;
    }

    private static Path resolveApplicationPath(Path appDirectory, String relativePath) throws IOException {
        if (isBlank(relativePath)) {
            throw new IOException("Update target path is blank");
        }
        Path target = appDirectory.resolve(relativePath).normalize();
        if (target.equals(appDirectory) || !target.startsWith(appDirectory)) {
            throw new IOException("Update target path escapes the application directory");
        }
        Path current = appDirectory;
        for (Path segment : appDirectory.relativize(target)) {
            current = current.resolve(segment);
            if (Files.isSymbolicLink(current)) {
                throw new IOException("Update target path contains a symbolic link");
            }
        }
        return target;
    }

    private static void verifyDownloadedFile(Path downloadedFile, FileInfo remoteFile) throws IOException {
        if (downloadedFile == null || !Files.isRegularFile(downloadedFile, LinkOption.NOFOLLOW_LINKS)) {
            throw new IOException("Downloaded update file is missing");
        }
        if (Files.size(downloadedFile) != remoteFile.fileSizeByte || Files.size(downloadedFile) > MAX_SINGLE_FILE_BYTES
                || !sha256(downloadedFile).equalsIgnoreCase(remoteFile.sha256)) {
            throw new IOException("Downloaded update file failed verification");
        }
    }

    private static void moveToBackup(Path target, Path appDirectory, Path backupSession, List<Runnable> rollbackOperations) throws IOException {
        Path backup = backupSession.resolve(appDirectory.relativize(target)).normalize();
        if (!backup.startsWith(backupSession)) {
            throw new IOException("Backup path escapes the update session");
        }
        Files.createDirectories(backup.getParent());
        moveIntoPlace(target, backup);
        rollbackOperations.add(() -> {
            try {
                deleteRecursively(target);
                moveIntoPlace(backup, target);
            } catch (IOException exception) {
                log("ERROR: rollback failed: " + exception.getMessage());
            }
        });
    }

    static void extractZip(Path archive, Path destination, String expectedTopLevelDirectory) throws IOException {
        Files.createDirectories(destination);
        int entryCount = 0;
        long extractedBytes = 0;
        byte[] buffer = new byte[8192];
        try (ZipInputStream zipInput = new ZipInputStream(new BufferedInputStream(Files.newInputStream(archive)))) {
            ZipEntry entry;
            while ((entry = zipInput.getNextEntry()) != null) {
                if (++entryCount > MAX_ZIP_ENTRIES) {
                    throw new IOException("ZIP archive has too many entries");
                }
                String entryName = entry.getName();
                int separator = entryName.indexOf('/');
                String topLevel = separator >= 0 ? entryName.substring(0, separator) : entryName;
                if (!expectedTopLevelDirectory.equals(topLevel)) {
                    throw new IOException("ZIP entry is outside the expected top-level directory");
                }
                Path output = destination.resolve(entryName).normalize();
                if (!output.startsWith(destination)) {
                    throw new IOException("ZIP entry escapes the staging directory");
                }
                if (entry.isDirectory()) {
                    Files.createDirectories(output);
                } else {
                    Files.createDirectories(output.getParent());
                    try (OutputStream out = Files.newOutputStream(output, StandardOpenOption.CREATE_NEW)) {
                        int read;
                        while ((read = zipInput.read(buffer)) != -1) {
                            extractedBytes = Math.addExact(extractedBytes, read);
                            if (extractedBytes > MAX_ZIP_UNCOMPRESSED_BYTES) {
                                throw new IOException("ZIP archive exceeds the uncompressed size limit");
                            }
                            out.write(buffer, 0, read);
                        }
                    }
                }
                zipInput.closeEntry();
            }
        }
    }

    private static void saveLocalVersion(VersionMetadata metadata, Path appDirectory) throws IOException {
        Path target = appDirectory.resolve("local_version.json");
        Path temporary = Files.createTempFile(appDirectory, ".local_version-", ".json");
        try {
            OBJECT_MAPPER.writerWithDefaultPrettyPrinter().writeValue(temporary.toFile(), metadata);
            moveIntoPlace(temporary, target);
        } finally {
            Files.deleteIfExists(temporary);
        }
    }

    private static void cleanupCommittedUpdate(Map<String, Path> downloadedFiles, Path stagingDirectory) {
        for (Path downloadedFile : downloadedFiles.values()) {
            try {
                Files.deleteIfExists(downloadedFile);
            } catch (IOException exception) {
                log("WARN: failed to remove downloaded update file: " + exception.getMessage());
            }
        }
        try {
            deleteRecursively(stagingDirectory);
        } catch (IOException exception) {
            log("WARN: failed to remove update staging directory: " + exception.getMessage());
        }
    }

    private static boolean restartMainApplication(String restartUri, Path appDirectory) {
        try {
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(restartUri));
                return true;
            }
        } catch (Exception exception) {
            log("WARN: protocol restart failed: " + exception.getMessage());
        }
        Path launcher = findApplicationLauncher(appDirectory);
        if (launcher == null) {
            return false;
        }
        try {
            new ProcessBuilder(launcher.toString()).start();
            return true;
        } catch (IOException exception) {
            log("WARN: launcher restart failed: " + exception.getMessage());
            return false;
        }
    }

    private static Path findApplicationLauncher(Path appDirectory) {
        List<String> candidates = List.of("chat2db-community.exe", "Chat2DB Community.exe", "Chat2DB.exe");
        for (String candidate : candidates) {
            Path launcher = appDirectory.resolve(candidate);
            if (Files.isRegularFile(launcher, LinkOption.NOFOLLOW_LINKS) && !Files.isSymbolicLink(launcher)) {
                return launcher;
            }
        }
        return null;
    }

    private static String sha256(Path file) throws IOException {
        try (InputStream in = Files.newInputStream(file)) {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] buffer = new byte[8192];
            int read;
            while ((read = in.read(buffer)) != -1) {
                digest.update(buffer, 0, read);
            }
            StringBuilder result = new StringBuilder();
            for (byte value : digest.digest()) {
                result.append(String.format("%02x", value));
            }
            return result.toString();
        } catch (NoSuchAlgorithmException exception) {
            throw new IOException("SHA-256 is unavailable", exception);
        }
    }

    private static void moveIntoPlace(Path source, Path target) throws IOException {
        Files.createDirectories(target.getParent());
        try {
            Files.move(source, target, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException exception) {
            Files.move(source, target, StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private static void deleteRecursively(Path path) throws IOException {
        if (!Files.exists(path, LinkOption.NOFOLLOW_LINKS)) {
            return;
        }
        if (Files.isDirectory(path, LinkOption.NOFOLLOW_LINKS)) {
            try (var entries = Files.newDirectoryStream(path)) {
                for (Path entry : entries) {
                    deleteRecursively(entry);
                }
            }
        }
        Files.deleteIfExists(path);
    }

    private static void deleteQuietly(Path path) {
        try {
            deleteRecursively(path);
        } catch (IOException exception) {
            log("ERROR: rollback cleanup failed: " + exception.getMessage());
        }
    }

    private static boolean isBlank(String value) {
        return value == null || value.trim().isEmpty();
    }

    private static void log(String message) {
        System.out.println("[chat2db-updater] " + message);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    static class UpdatePlan {
        public List<FileUpdateAction> tasks;
        public Map<String, String> downloadedFiles;
        public VersionMetadata remoteMetadata;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    static class VersionMetadata {
        public String version;
        public List<FileInfo> files;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    static class FileUpdateAction {
        public FileInfo remoteFileInfo;
        public FileInfo localFileInfo;
        public String actionType;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    static class FileInfo {
        public String id;
        public String localTargetName;
        public String sha256;
        public String type;
        public long fileSizeByte;
        public boolean deleted;
    }
}
