package ai.chat2db.community.start.ai.subscription.appserver.internal;

import ai.chat2db.community.start.ai.subscription.appserver.AppServerDisabledReason;
import ai.chat2db.community.start.ai.subscription.appserver.AppServerException;
import ai.chat2db.community.start.ai.subscription.appserver.AppServerMcpEndpoint;
import ai.chat2db.community.start.ai.subscription.appserver.Chat2dbMcpToolPolicy;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Creates an isolated Chat2DB-owned Codex home, empty workdir, and restrictive config.toml.
 * Forces keyring credential storage and disables native tool surfaces Chat2DB does not own.
 * <p>
 * When an MCP endpoint is supplied, only a loopback URL and env-var header mapping are written;
 * capability material is never written to disk.
 */
public final class AppServerHomeLayout {

    public static final String MCP_SERVER_ID = "chat2db_subscription";

    private final Path codexHome;
    private final Path workdir;

    public AppServerHomeLayout(Path codexHome, Path workdir) {
        this.codexHome = Objects.requireNonNull(codexHome, "codexHome");
        this.workdir = Objects.requireNonNull(workdir, "workdir");
    }

    public Path codexHome() {
        return codexHome;
    }

    public Path workdir() {
        return workdir;
    }

    public void prepare() {
        prepare(null);
    }

    public void prepare(AppServerMcpEndpoint mcpEndpoint) {
        try {
            Files.createDirectories(codexHome);
            Files.createDirectories(workdir);
            try (var entries = Files.list(workdir)) {
                if (entries.findAny().isPresent()) {
                    throw new AppServerException(
                            AppServerDisabledReason.RUNTIME_GATES_NOT_SATISFIED,
                            "app-server work directory must be empty");
                }
            }
            rejectFileCredentialFallback();
            Path config = codexHome.resolve("config.toml");
            Files.writeString(config, restrictiveConfigToml(mcpEndpoint), StandardCharsets.UTF_8);
        } catch (IOException ex) {
            throw new AppServerException(
                    AppServerDisabledReason.RUNTIME_GATES_NOT_SATISFIED,
                    "unable to prepare isolated app-server home",
                    ex);
        }
    }

    void rejectFileCredentialFallback() throws IOException {
        Path authJson = codexHome.resolve("auth.json");
        if (Files.exists(authJson)) {
            // Never read token material; presence of a file store fails closed.
            throw new AppServerException(
                    AppServerDisabledReason.KEYRING_UNAVAILABLE,
                    "file credential store auth.json is forbidden; keyring-only required");
        }
    }

    static String restrictiveConfigToml() {
        return restrictiveConfigToml(null);
    }

    static String restrictiveConfigToml(AppServerMcpEndpoint mcpEndpoint) {
        List<String> lines = new ArrayList<>();
        lines.add("# Generated by Chat2DB Community. Do not place credential material here.");
        lines.add("cli_auth_credentials_store = \"keyring\"");
        lines.add("mcp_oauth_credentials_store = \"keyring\"");
        lines.add("approval_policy = \"never\"");
        // Empty isolated workdir: workspace-write keeps FS contained while allowing network for
        // loopback MCP HTTP tools/call. read-only sets network_access=false and can stall CallTool.
        lines.add("sandbox_mode = \"workspace-write\"");
        lines.add("web_search = \"disabled\"");
        lines.add("history.persistence = \"none\"");
        lines.add("");
        lines.add("[sandbox_workspace_write]");
        lines.add("network_access = true");
        lines.add("exclude_tmpdir_env_var = true");
        lines.add("exclude_slash_tmp = true");
        lines.add("");
        lines.add("[features]");
        lines.add("shell_tool = false");
        lines.add("unified_exec = false");
        lines.add("shell_snapshot = false");
        // Nested CodeMode MCP hangs before HTTP tools/call. Keep CodeMode off.
        lines.add("code_mode = false");
        lines.add("code_mode_host = false");
        lines.add("code_mode_only = false");
        lines.add("js_repl = false");
        lines.add("js_repl_tools_only = false");
        // Prefer direct MCP schema. ChatGPT may still force AlwaysDefer; deferred path must complete
        // tools/call (serverRequest auto-approve + network_access). Keep explicit false anyway.
        lines.add("tool_search = false");
        lines.add("tool_search_always_defer_mcp_tools = false");
        lines.add("search_tool = false");
        lines.add("request_permissions = false");
        lines.add("hooks = false");
        lines.add("multi_agent = false");
        lines.add("apps = false");
        lines.add("enable_mcp_apps = false");
        lines.add("tool_suggest = false");
        lines.add("plugins = false");
        // System skills encourage non-Chat2DB tool routing; keep disabled for parity with API tools.
        // Note: v0.144.6 logs "unknown feature key: skills" but ignores it safely.
        lines.add("skills = false");
        lines.add("in_app_browser = false");
        lines.add("browser_use = false");
        lines.add("browser_use_full_cdp_access = false");
        lines.add("browser_use_external = false");
        lines.add("computer_use = false");
        lines.add("remote_plugin = false");
        lines.add("plugin_sharing = false");
        lines.add("image_generation = false");
        lines.add("skill_mcp_dependency_install = false");
        lines.add("guardian_approval = false");
        lines.add("goals = false");
        lines.add("tool_call_mcp_elicitation = false");
        lines.add("auth_elicitation = false");
        lines.add("workspace_dependencies = false");
        lines.add("network_proxy = false");
        lines.add("");
        lines.add("[apps._default]");
        lines.add("enabled = false");
        lines.add("");

        if (mcpEndpoint != null) {
            // Fail closed for non-loopback is enforced by AppServerMcpEndpoint construction.
            // Capability value is never written — only the env var name for header population.
            lines.add("[mcp_servers." + MCP_SERVER_ID + "]");
            lines.add("url = \"" + escapeToml(mcpEndpoint.url()) + "\"");
            lines.add("enabled_tools = ["
                    + Chat2dbMcpToolPolicy.ORDERED_DATABASE_TOOLS.stream()
                    .map(tool -> "\"" + escapeToml(tool) + "\"")
                    .collect(java.util.stream.Collectors.joining(", "))
                    + "]");
            lines.add("supports_parallel_tool_calls = true");
            lines.add("startup_timeout_ms = 15000");
            lines.add("");
            lines.add("[mcp_servers." + MCP_SERVER_ID + ".env_http_headers]");
            lines.add("\"" + escapeToml(mcpEndpoint.capabilityHeaderName()) + "\" = \""
                    + escapeToml(mcpEndpoint.capabilityEnvVarName()) + "\"");
            lines.add("");
        }
        return String.join("\n", lines);
    }

    private static String escapeToml(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
