CREATE TABLE agent_run_event (
    event_order BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(128) NOT NULL UNIQUE,
    run_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    content CLOB,
    payload_json CLOB NOT NULL,
    occurred_at BIGINT NOT NULL,
    persisted_at BIGINT NOT NULL,
    CONSTRAINT fk_agent_run_event_run
        FOREIGN KEY (run_id) REFERENCES agent_run(id)
);

CREATE INDEX idx_agent_run_event_run_order
    ON agent_run_event(run_id, event_order ASC);
