-- MYSQL-OBJ-011: Cleanup

DROP FUNCTION IF EXISTS `obj011_add`;
DROP PROCEDURE IF EXISTS `obj011_add`;
DROP FUNCTION IF EXISTS `obj011_compute`;
DROP PROCEDURE IF EXISTS `obj011_swap`;
DROP TABLE IF EXISTS `obj011_data`;
