CREATE USER IF NOT EXISTS 'chat2db_obj014'@'%' IDENTIFIED BY 'chat2db_obj014';
GRANT SELECT, CREATE, ALTER, DROP, INDEX ON chat2db_mysql_obj_014.* TO 'chat2db_obj014'@'%';
GRANT CREATE TABLESPACE, PROCESS ON *.* TO 'chat2db_obj014'@'%';
FLUSH PRIVILEGES;
