SELECT TABLESPACE_NAME, ENGINE, TABLESPACE_TYPE
FROM INFORMATION_SCHEMA.TABLESPACES
WHERE TABLESPACE_NAME IN ('chat2db_ts_general', 'chat2db_ts_empty')
ORDER BY TABLESPACE_NAME;

SELECT FILE_NAME, TABLESPACE_NAME
FROM INFORMATION_SCHEMA.FILES
WHERE TABLESPACE_NAME IN ('chat2db_ts_general', 'chat2db_ts_empty')
ORDER BY TABLESPACE_NAME, FILE_NAME;

SELECT REPLACE(I.NAME, '/', '.') AS OBJECT_NAME
FROM INFORMATION_SCHEMA.INNODB_TABLES I
JOIN INFORMATION_SCHEMA.INNODB_TABLESPACES S ON S.SPACE = I.SPACE
WHERE S.NAME = 'chat2db_ts_general'
ORDER BY OBJECT_NAME;
