SELECT SPACE, NAME, SPACE_TYPE, PAGE_SIZE
FROM INFORMATION_SCHEMA.INNODB_SYS_TABLESPACES
WHERE SPACE_TYPE = 'General'
  AND NAME IN ('chat2db_ts_general', 'chat2db_ts_empty')
ORDER BY NAME;

SELECT REPLACE(I.NAME, '/', '.') AS OBJECT_NAME
FROM INFORMATION_SCHEMA.INNODB_SYS_TABLES I
JOIN INFORMATION_SCHEMA.INNODB_SYS_TABLESPACES S ON S.SPACE = I.SPACE
WHERE S.NAME = 'chat2db_ts_general'
ORDER BY OBJECT_NAME;
