import { DatabaseTypeCode } from './common';

export enum IdentifierQuoteMode {
  NONE = 'NONE',
  DOUBLE_QUOTE = 'DOUBLE_QUOTE',
  SQUARE_BRACKET = 'SQUARE_BRACKET',
  BACKTICK = 'BACKTICK',
}

export const databaseCapabilities = {
  routineOperationSupported: [DatabaseTypeCode.MYSQL],
  accountManageSupported: [DatabaseTypeCode.MYSQL],
  databaseDeleteSupported: [DatabaseTypeCode.MYSQL, DatabaseTypeCode.POSTGRESQL],
  schemaDeleteSupported: [DatabaseTypeCode.POSTGRESQL],
  createDatabaseUnsupported: [DatabaseTypeCode.H2],
  createDatabaseCharsetSupported: [DatabaseTypeCode.MYSQL],
  createDatabaseCollationSupported: [DatabaseTypeCode.MYSQL],
  createSchemaUnsupported: [DatabaseTypeCode.ORACLE, DatabaseTypeCode.OSCAR],
  importExportUnsupported: [
    DatabaseTypeCode.REDIS,
    DatabaseTypeCode.H2,
    DatabaseTypeCode.PRESTO,
    DatabaseTypeCode.MONGODB,
    DatabaseTypeCode.SNOWFLAKE,
    DatabaseTypeCode.KYLIN,
    DatabaseTypeCode.KINGBASE,
    DatabaseTypeCode.HIVE,
  ],
  generateJavaClassSupported: [
    DatabaseTypeCode.CLICKHOUSE,
    DatabaseTypeCode.DB2,
    DatabaseTypeCode.DM,
    DatabaseTypeCode.KINGBASE,
    DatabaseTypeCode.POSTGRESQL,
    DatabaseTypeCode.SQLITE,
    DatabaseTypeCode.SQLSERVER,
    DatabaseTypeCode.MYSQL,
    DatabaseTypeCode.ORACLE,
  ],
  backendCompletionSupported: [DatabaseTypeCode.MYSQL],
  backendEditorHintsSupported: [DatabaseTypeCode.MYSQL, DatabaseTypeCode.POSTGRESQL],
  tableEditorMysqlBaseInfoSupported: [DatabaseTypeCode.MYSQL],
  tableEditorMysqlIndexMethodSupported: [DatabaseTypeCode.MYSQL],
  tableEditorOracleIndexColumnHidden: [DatabaseTypeCode.ORACLE],
  tableEditorSqliteIncludeCollationSupported: [DatabaseTypeCode.SQLITE],
  tableEditorSqliteExistingColumnReadonly: [DatabaseTypeCode.SQLITE],
  tableEditorSqlServerSparseSupported: [DatabaseTypeCode.SQLSERVER],
  redisTreeDataSourceTypes: [DatabaseTypeCode.REDIS],
  mongodbTreeDataSourceTypes: [DatabaseTypeCode.MONGODB],
  openTableIdentifierQuote: {
    [IdentifierQuoteMode.DOUBLE_QUOTE]: [
      DatabaseTypeCode.ORACLE,
      DatabaseTypeCode.OSCAR,
      DatabaseTypeCode.SQLITE,
      DatabaseTypeCode.POSTGRESQL,
      DatabaseTypeCode.H2,
      DatabaseTypeCode.DB2,
      DatabaseTypeCode.KINGBASE,
      DatabaseTypeCode.DM,
    ],
    [IdentifierQuoteMode.SQUARE_BRACKET]: [DatabaseTypeCode.SQLSERVER],
    [IdentifierQuoteMode.BACKTICK]: [DatabaseTypeCode.MYSQL, DatabaseTypeCode.CLICKHOUSE, DatabaseTypeCode.MARIADB],
  },
  sqlCompletionIdentifierQuote: {
    [IdentifierQuoteMode.DOUBLE_QUOTE]: [
      DatabaseTypeCode.POSTGRESQL,
      DatabaseTypeCode.ORACLE,
      DatabaseTypeCode.OSCAR,
      DatabaseTypeCode.DB2,
      DatabaseTypeCode.DM,
      DatabaseTypeCode.H2,
      DatabaseTypeCode.SQLITE,
      DatabaseTypeCode.OCEANBASE_ORACLE,
      DatabaseTypeCode.KINGBASE,
      DatabaseTypeCode.SNOWFLAKE,
      DatabaseTypeCode.OPENGAUSS,
      DatabaseTypeCode.SUNDB,
      DatabaseTypeCode.COCKROACHDB,
      DatabaseTypeCode.KYLIN,
      DatabaseTypeCode.XUGUDB,
      DatabaseTypeCode.PRESTO,
    ],
    [IdentifierQuoteMode.SQUARE_BRACKET]: [DatabaseTypeCode.SQLSERVER],
    [IdentifierQuoteMode.BACKTICK]: [
      DatabaseTypeCode.MYSQL,
      DatabaseTypeCode.MARIADB,
      DatabaseTypeCode.TIDB,
      DatabaseTypeCode.CLICKHOUSE,
      DatabaseTypeCode.OCEANBASE,
      DatabaseTypeCode.HIVE,
    ],
  },
} as const;
